// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: proto/souslet/v1/souslet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Correlates a request with its response(s). sous-api generates one per
	// command or proxied HTTP request; souslet echoes it back on every
	// reply so concurrent operations resolve independently of arrival order.
	StreamId string `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*Envelope_Snapshot
	//	*Envelope_Deploy
	//	*Envelope_Undeploy
	//	*Envelope_Plan
	//	*Envelope_Fetch
	//	*Envelope_DeleteWeights
	//	*Envelope_HttpReqHead
	//	*Envelope_HttpReqChunk
	//	*Envelope_DeployResult
	//	*Envelope_UndeployResult
	//	*Envelope_PlanResult
	//	*Envelope_FetchProgress
	//	*Envelope_DeleteWeightsResult
	//	*Envelope_HttpRespHead
	//	*Envelope_HttpRespChunk
	//	*Envelope_Heartbeat
	//	*Envelope_Error
	Payload isEnvelope_Payload `protobuf_oneof:"payload"`
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_souslet_v1_souslet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_souslet_v1_souslet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_souslet_v1_souslet_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (m *Envelope) GetPayload() isEnvelope_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Envelope) GetSnapshot() *NodeSnapshot {
	if x, ok := x.GetPayload().(*Envelope_Snapshot); ok {
		return x.Snapshot
	}
	return nil
}

func (x *Envelope) GetDeploy() *DeployCommand {
	if x, ok := x.GetPayload().(*Envelope_Deploy); ok {
		return x.Deploy
	}
	return nil
}

func (x *Envelope) GetUndeploy() *UndeployCommand {
	if x, ok := x.GetPayload().(*Envelope_Undeploy); ok {
		return x.Undeploy
	}
	return nil
}

func (x *Envelope) GetPlan() *PlanCommand {
	if x, ok := x.GetPayload().(*Envelope_Plan); ok {
		return x.Plan
	}
	return nil
}

func (x *Envelope) GetFetch() *FetchCommand {
	if x, ok := x.GetPayload().(*Envelope_Fetch); ok {
		return x.Fetch
	}
	return nil
}

func (x *Envelope) GetDeleteWeights() *DeleteWeightsCommand {
	if x, ok := x.GetPayload().(*Envelope_DeleteWeights); ok {
		return x.DeleteWeights
	}
	return nil
}

func (x *Envelope) GetHttpReqHead() *HTTPRequestHead {
	if x, ok := x.GetPayload().(*Envelope_HttpReqHead); ok {
		return x.HttpReqHead
	}
	return nil
}

func (x *Envelope) GetHttpReqChunk() *HTTPRequestChunk {
	if x, ok := x.GetPayload().(*Envelope_HttpReqChunk); ok {
		return x.HttpReqChunk
	}
	return nil
}

func (x *Envelope) GetDeployResult() *DeployResult {
	if x, ok := x.GetPayload().(*Envelope_DeployResult); ok {
		return x.DeployResult
	}
	return nil
}

func (x *Envelope) GetUndeployResult() *UndeployResult {
	if x, ok := x.GetPayload().(*Envelope_UndeployResult); ok {
		return x.UndeployResult
	}
	return nil
}

func (x *Envelope) GetPlanResult() *PlanResult {
	if x, ok := x.GetPayload().(*Envelope_PlanResult); ok {
		return x.PlanResult
	}
	return nil
}

func (x *Envelope) GetFetchProgress() *FetchProgress {
	if x, ok := x.GetPayload().(*Envelope_FetchProgress); ok {
		return x.FetchProgress
	}
	return nil
}

func (x *Envelope) GetDeleteWeightsResult() *DeleteWeightsResult {
	if x, ok := x.GetPayload().(*Envelope_DeleteWeightsResult); ok {
		return x.DeleteWeightsResult
	}
	return nil
}

func (x *Envelope) GetHttpRespHead() *HTTPResponseHead {
	if x, ok := x.GetPayload().(*Envelope_HttpRespHead); ok {
		return x.HttpRespHead
	}
	return nil
}

func (x *Envelope) GetHttpRespChunk() *HTTPResponseChunk {
	if x, ok := x.GetPayload().(*Envelope_HttpRespChunk); ok {
		return x.HttpRespChunk
	}
	return nil
}

func (x *Envelope) GetHeartbeat() *Heartbeat {
	if x, ok := x.GetPayload().(*Envelope_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (x *Envelope) GetError() *Error {
	if x, ok := x.GetPayload().(*Envelope_Error); ok {
		return x.Error
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Snapshot struct {
	// souslet -> API, sent once immediately after Connect and again after
	// every reconnect. Full state, not a diff.
	Snapshot *NodeSnapshot `protobuf:"bytes,10,opt,name=snapshot,proto3,oneof"`
}

type Envelope_Deploy struct {
	// API -> souslet
	Deploy *DeployCommand `protobuf:"bytes,20,opt,name=deploy,proto3,oneof"`
}

type Envelope_Undeploy struct {
	Undeploy *UndeployCommand `protobuf:"bytes,21,opt,name=undeploy,proto3,oneof"`
}

type Envelope_Plan struct {
	Plan *PlanCommand `protobuf:"bytes,22,opt,name=plan,proto3,oneof"`
}

type Envelope_Fetch struct {
	Fetch *FetchCommand `protobuf:"bytes,23,opt,name=fetch,proto3,oneof"`
}

type Envelope_DeleteWeights struct {
	DeleteWeights *DeleteWeightsCommand `protobuf:"bytes,24,opt,name=delete_weights,json=deleteWeights,proto3,oneof"`
}

type Envelope_HttpReqHead struct {
	HttpReqHead *HTTPRequestHead `protobuf:"bytes,25,opt,name=http_req_head,json=httpReqHead,proto3,oneof"`
}

type Envelope_HttpReqChunk struct {
	HttpReqChunk *HTTPRequestChunk `protobuf:"bytes,26,opt,name=http_req_chunk,json=httpReqChunk,proto3,oneof"`
}

type Envelope_DeployResult struct {
	// souslet -> API
	DeployResult *DeployResult `protobuf:"bytes,30,opt,name=deploy_result,json=deployResult,proto3,oneof"`
}

type Envelope_UndeployResult struct {
	UndeployResult *UndeployResult `protobuf:"bytes,31,opt,name=undeploy_result,json=undeployResult,proto3,oneof"`
}

type Envelope_PlanResult struct {
	PlanResult *PlanResult `protobuf:"bytes,32,opt,name=plan_result,json=planResult,proto3,oneof"`
}

type Envelope_FetchProgress struct {
	FetchProgress *FetchProgress `protobuf:"bytes,33,opt,name=fetch_progress,json=fetchProgress,proto3,oneof"`
}

type Envelope_DeleteWeightsResult struct {
	DeleteWeightsResult *DeleteWeightsResult `protobuf:"bytes,34,opt,name=delete_weights_result,json=deleteWeightsResult,proto3,oneof"`
}

type Envelope_HttpRespHead struct {
	HttpRespHead *HTTPResponseHead `protobuf:"bytes,35,opt,name=http_resp_head,json=httpRespHead,proto3,oneof"`
}

type Envelope_HttpRespChunk struct {
	HttpRespChunk *HTTPResponseChunk `protobuf:"bytes,36,opt,name=http_resp_chunk,json=httpRespChunk,proto3,oneof"`
}

type Envelope_Heartbeat struct {
	// either direction
	Heartbeat *Heartbeat `protobuf:"bytes,40,opt,name=heartbeat,proto3,oneof"`
}

type Envelope_Error struct {
	Error *Error `protobuf:"bytes,41,opt,name=error,proto3,oneof"`
}

func (*Envelope_Snapshot) isEnvelope_Payload() {}

func (*Envelope_Deploy) isEnvelope_Payload() {}

func (*Envelope_Undeploy) isEnvelope_Payload() {}

func (*Envelope_Plan) isEnvelope_Payload() {}

func (*Envelope_Fetch) isEnvelope_Payload() {}

func (*Envelope_DeleteWeights) isEnvelope_Payload() {}

func (*Envelope_HttpReqHead) isEnvelope_Payload() {}

func (*Envelope_HttpReqChunk) isEnvelope_Payload() {}

func (*Envelope_DeployResult) isEnvelope_Payload() {}

func (*Envelope_UndeployResult) isEnvelope_Payload() {}

func (*Envelope_PlanResult) isEnvelope_Payload() {}

func (*Envelope_FetchProgress) isEnvelope_Payload() {}

func (*Envelope_DeleteWeightsResult) isEnvelope_Payload() {}

func (*Envelope_HttpRespHead) isEnvelope_Payload() {}

func (*Envelope_HttpRespChunk) isEnvelope_Payload() {}

func (*Envelope_Heartbeat) isEnvelope_Payload() {}

func (*Envelope_Error) isEnvelope_Payload() {}

type NodeSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId            string             `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PoolGib           float64            `protobuf:"fixed64,2,opt,name=pool_gib,json=poolGib,proto3" json:"pool_gib,omitempty"`
	ReserveGib        float64            `protobuf:"fixed64,3,opt,name=reserve_gib,json=reserveGib,proto3" json:"reserve_gib,omitempty"`
	Deployments       []*DeploymentState `protobuf:"bytes,4,rep,name=deployments,proto3" json:"deployments,omitempty"`
	CachedWeightRepos []string           `protobuf:"bytes,5,rep,name=cached_weight_repos,json=cachedWeightRepos,proto3" json:"cached_weight_repos,omitempty"`
}

func (x *NodeSnapshot) Reset() {
	*x = NodeSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_souslet_v1_souslet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSnapshot) ProtoMessage() {}

func (x *NodeSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_souslet_v1_souslet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSnapshot.ProtoReflect.Descriptor instead.
func (*NodeSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_souslet_v1_souslet_proto_rawDescGZIP(), []int{1}
}

func (x *NodeSnapshot) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeSnapshot) GetPoolGib() float64 {
	if x != nil {
		return x.PoolGib
	}
	return 0
}

func (x *NodeSnapshot) GetReserveGib() float64 {
	if x != nil {
		return x.ReserveGib
	}
	return 0
}

func (x *NodeSnapshot) GetDeployments() []*DeploymentState {
	if x != nil {
		return x.Deployments
	}
	return nil
}

func (x *NodeSnapshot) GetCachedWeightRepos() []string {
	if x != nil {
		return x.CachedWeightRepos
	}
	return nil
}

type DeploymentState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeId   string  `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	HostPort   int32   `protobuf:"varint,2,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	Phase      string  `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	WeightsGib float64 `protobuf:"fixed64,4,opt,name=weights_gib,json=weightsGib,proto3" json:"weights_gib,omitempty"`
	KvGib      float64 `protobuf:"fixed64,5,opt,name=kv_gib,json=kvGib,proto3" json:"kv_gib,omitempty"`
}

func (x *DeploymentState) Reset() {
	*x = DeploymentState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_souslet_v1_souslet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeploymentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentState) ProtoMessage() {}

func (x *DeploymentState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_souslet_v1_souslet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentState.ProtoReflect.Descriptor instead.
func (*DeploymentState) Descriptor() ([]byte, []int) {
	return file_proto_souslet_v1_souslet_proto_rawDescGZIP(), []int{2}
}

func (x *DeploymentState) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *DeploymentState) GetHostPort() int32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *DeploymentState) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *DeploymentState) GetWeightsGib() float64 {
	if x != nil {
		return x.WeightsGib
	}
	return 0
}

func (x *DeploymentState) GetKvGib() float64 {
	if x != nil {
		return x.KvGib
	}
	return 0
}

type DeployCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeId   string `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	RecipeYaml string `protobuf:"bytes,2,opt,name=recipe_yaml,json=recipeYaml,proto3" json:"recipe_yaml,omitempty"` // full recipe, so souslet needs no catalog of its own
	WantPort   int32  `protobuf:"varint,3,opt,name=want_port,json=wantPort,proto3" json:"want_port,omitempty"`
	Force      bool   `protobuf:"varint,4,opt,name=force,proto3" json:"force,omitempty"`
}

func (x *DeployCommand) Reset() {
	*x = DeployCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_souslet_v1_souslet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployCommand) ProtoMessage() {}

func (x *DeployCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_souslet_v1_souslet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployCommand.ProtoReflect.Descriptor instead.
func (*DeployCommand) Descriptor() ([]byte, []int) {
	return file_proto_souslet_v1_souslet_proto_rawDescGZIP(), []int{3}
}

func (x *DeployCommand) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *DeployCommand) GetRecipeYaml() string {
	if x != nil {
		return x.RecipeYaml
	}
	return ""
}

func (x *DeployCommand) GetWantPort() int32 {
	if x != nil {
		return x.WantPort
	}
	return 0
}

func (x *DeployCommand) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DeployResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeId    string `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	HostPort    int32  `protobuf:"varint,2,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	ContainerId string `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Error       string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"` // empty on success
}

func (x *DeployResult) Reset() {
	*x = DeployResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_souslet_v1_souslet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResult) ProtoMessage() {}

func (x *DeployResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_souslet_v1_souslet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResult.ProtoReflect.Descriptor instead.
func (*DeployResult) Descriptor() ([]byte, []int) {
	return file_proto_souslet_v1_souslet_proto_rawDescGZIP(), []int{4}
}

func (x *DeployResult) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *DeployResult) GetHostPort() int32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *DeployResult) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *DeployResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UndeployCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeId string `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
}

func (x *UndeployCommand) Reset() {
	*x = UndeployCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_souslet_v1_souslet_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UndeployCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeployCommand) ProtoMessage() {}

func (x *UndeployCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_souslet_v1_souslet_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeployCommand.ProtoReflect.Descriptor instead.
func (*UndeployCommand) Descriptor() ([]byte, []int) {
	return file_proto_souslet_v1_souslet_proto_rawDescGZIP(), []int{5}
}

func (x *UndeployCommand) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

type UndeployResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeId string `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	Error    string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *UndeployResult) Reset() {
	*x = UndeployResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_souslet_v1_souslet_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UndeployResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeployResult) ProtoMessage() {}

func (x *UndeployResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_souslet_v1_souslet_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeployResult.ProtoReflect.Descriptor instead.
func (*UndeployResult) Descriptor() ([]byte, []int) {
	return file_proto_souslet_v1_souslet_proto_rawDescGZIP(), []int{6}
}

func (x *UndeployResult) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *UndeployResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PlanCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeId    string  `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	IncomingGib float64 `protobuf:"fixed64,2,opt,name=incoming_gib,json=incomingGib,proto3" json:"incoming_gib,omitempty"`
}

func (x *PlanCommand) Reset() {
	*x = PlanCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_souslet_v1_souslet_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlanCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanCommand) ProtoMessage() {}

func (x *PlanCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_souslet_v1_souslet_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanCommand.ProtoReflect.Descriptor instead.
func (*PlanCommand) Descriptor() ([]byte, []int) {
	return file_proto_souslet_v1_souslet_proto_rawDescGZIP(), []int{7}
}

func (x *PlanCommand) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *PlanCommand) GetIncomingGib() float64 {
	if x != nil {
		return x.IncomingGib
	}
	return 0
}

type PlanResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fits         bool     `protobuf:"varint,1,opt,name=fits,proto3" json:"fits,omitempty"`
	CommittedGib float64  `protobuf:"fixed64,2,opt,name=committed_gib,json=committedGib,proto3" json:"committed_gib,omitempty"`
	MarginGib    float64  `protobuf:"fixed64,3,opt,name=margin_gib,json=marginGib,proto3" json:"margin_gib,omitempty"`
	MustFree     []string `protobuf:"bytes,4,rep,name=must_free,json=mustFree,proto3" json:"must_free,omitempty"`
}

func (x *PlanResult) Reset() {
	*x = PlanResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_souslet_v1_souslet_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResult) ProtoMessage() {}

func (x *PlanResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_souslet_v1_souslet_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResult.ProtoReflect.Descriptor instead.
func (*PlanResult) Descriptor() ([]byte, []int) {
	return file_proto_souslet_v1_souslet_proto_rawDescGZIP(), []int{8}
}

func (x *PlanResult) GetFits() bool {
	if x != nil {
		return x.Fits
	}
	return false
}

func (x *PlanResult) GetCommittedGib() float64 {
	if x != nil {
		return x.CommittedGib
	}
	return 0
}

func (x *PlanResult) GetMarginGib() float64 {
	if x != nil {
		return x.MarginGib
	}
	return 0
}

func (x *PlanResult) GetMustFree() []string {
	if x != nil {
		return x.MustFree
	}
	return nil
}

type FetchCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repo string `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
}

func (x *FetchCommand) Reset() {
	*x = FetchCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_souslet_v1_souslet_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchCommand) ProtoMessage() {}

func (x *FetchCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_souslet_v1_souslet_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchCommand.ProtoReflect.Descriptor instead.
func (*FetchCommand) Descriptor() ([]byte, []int) {
	return file_proto_souslet_v1_souslet_proto_rawDescGZIP(), []int{9}
}

func (x *FetchCommand) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type FetchProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repo  string `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Phase string `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"` // downloading|done|failed|absent
	Bytes int64  `protobuf:"varint,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Total int64  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *FetchProgress) Reset() {
	*x = FetchProgress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_souslet_v1_souslet_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchProgress) ProtoMessage() {}

func (x *FetchProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_souslet_v1_souslet_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchProgress.ProtoReflect.Descriptor instead.
func (*FetchProgress) Descriptor() ([]byte, []int) {
	return file_proto_souslet_v1_souslet_proto_rawDescGZIP(), []int{10}
}

func (x *FetchProgress) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *FetchProgress) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *FetchProgress) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *FetchProgress) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteWeightsCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repo  string `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Force bool   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
}

func (x *DeleteWeightsCommand) Reset() {
	*x = DeleteWeightsCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_souslet_v1_souslet_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWeightsCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWeightsCommand) ProtoMessage() {}

func (x *DeleteWeightsCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_souslet_v1_souslet_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWeightsCommand.ProtoReflect.Descriptor instead.
func (*DeleteWeightsCommand) Descriptor() ([]byte, []int) {
	return file_proto_souslet_v1_souslet_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteWeightsCommand) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *DeleteWeightsCommand) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DeleteWeightsResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repo       string `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	BytesFreed int64  `protobuf:"varint,2,opt,name=bytes_freed,json=bytesFreed,proto3" json:"bytes_freed,omitempty"`
	Error      string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeleteWeightsResult) Reset() {
	*x = DeleteWeightsResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_souslet_v1_souslet_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWeightsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWeightsResult) ProtoMessage() {}

func (x *DeleteWeightsResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_souslet_v1_souslet_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWeightsResult.ProtoReflect.Descriptor instead.
func (*DeleteWeightsResult) Descriptor() ([]byte, []int) {
	return file_proto_souslet_v1_souslet_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteWeightsResult) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *DeleteWeightsResult) GetBytesFreed() int64 {
	if x != nil {
		return x.BytesFreed
	}
	return 0
}

func (x *DeleteWeightsResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HTTPRequestHead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method  string            `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path    string            `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *HTTPRequestHead) Reset() {
	*x = HTTPRequestHead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_souslet_v1_souslet_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTPRequestHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRequestHead) ProtoMessage() {}

func (x *HTTPRequestHead) ProtoReflect() protoreflect.Message {
	mi := &file_proto_souslet_v1_souslet_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRequestHead.ProtoReflect.Descriptor instead.
func (*HTTPRequestHead) Descriptor() ([]byte, []int) {
	return file_proto_souslet_v1_souslet_proto_rawDescGZIP(), []int{13}
}

func (x *HTTPRequestHead) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HTTPRequestHead) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HTTPRequestHead) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type HTTPRequestChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Eof  bool   `protobuf:"varint,2,opt,name=eof,proto3" json:"eof,omitempty"`
}

func (x *HTTPRequestChunk) Reset() {
	*x = HTTPRequestChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_souslet_v1_souslet_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTPRequestChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRequestChunk) ProtoMessage() {}

func (x *HTTPRequestChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_souslet_v1_souslet_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRequestChunk.ProtoReflect.Descriptor instead.
func (*HTTPRequestChunk) Descriptor() ([]byte, []int) {
	return file_proto_souslet_v1_souslet_proto_rawDescGZIP(), []int{14}
}

func (x *HTTPRequestChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *HTTPRequestChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type HTTPResponseHead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32             `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Headers map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *HTTPResponseHead) Reset() {
	*x = HTTPResponseHead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_souslet_v1_souslet_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTPResponseHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPResponseHead) ProtoMessage() {}

func (x *HTTPResponseHead) ProtoReflect() protoreflect.Message {
	mi := &file_proto_souslet_v1_souslet_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPResponseHead.ProtoReflect.Descriptor instead.
func (*HTTPResponseHead) Descriptor() ([]byte, []int) {
	return file_proto_souslet_v1_souslet_proto_rawDescGZIP(), []int{15}
}

func (x *HTTPResponseHead) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HTTPResponseHead) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type HTTPResponseChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Eof  bool   `protobuf:"varint,2,opt,name=eof,proto3" json:"eof,omitempty"`
}

func (x *HTTPResponseChunk) Reset() {
	*x = HTTPResponseChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_souslet_v1_souslet_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTPResponseChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPResponseChunk) ProtoMessage() {}

func (x *HTTPResponseChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_souslet_v1_souslet_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPResponseChunk.ProtoReflect.Descriptor instead.
func (*HTTPResponseChunk) Descriptor() ([]byte, []int) {
	return file_proto_souslet_v1_souslet_proto_rawDescGZIP(), []int{16}
}

func (x *HTTPResponseChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *HTTPResponseChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnixSeconds int64 `protobuf:"varint,1,opt,name=unix_seconds,json=unixSeconds,proto3" json:"unix_seconds,omitempty"`
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_souslet_v1_souslet_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_souslet_v1_souslet_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_souslet_v1_souslet_proto_rawDescGZIP(), []int{17}
}

func (x *Heartbeat) GetUnixSeconds() int64 {
	if x != nil {
		return x.UnixSeconds
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_souslet_v1_souslet_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_souslet_v1_souslet_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_souslet_v1_souslet_proto_rawDescGZIP(), []int{18}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_souslet_v1_souslet_proto protoreflect.FileDescriptor

var file_proto_souslet_v1_souslet_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6f, 0x75, 0x73, 0x6c, 0x65, 0x74, 0x2f,
	0x76, 0x31, 0x2f, 0x73, 0x6f, 0x75, 0x73, 0x6c, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x73, 0x6f, 0x75, 0x73, 0x6c, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x22, 0xde, 0x08, 0x0a,
	0x08, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x36, 0x0a, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x6f, 0x75, 0x73, 0x6c,
	0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x48, 0x00, 0x52, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x33,
	0x0a, 0x06, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x73, 0x6f, 0x75, 0x73, 0x6c, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x06, 0x64, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x12, 0x39, 0x0a, 0x08, 0x75, 0x6e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x18,
	0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x6f, 0x75, 0x73, 0x6c, 0x65, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x55, 0x6e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x48, 0x00, 0x52, 0x08, 0x75, 0x6e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x12, 0x2d,
	0x0a, 0x04, 0x70, 0x6c, 0x61, 0x6e, 0x18, 0x16, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73,
	0x6f, 0x75, 0x73, 0x6c, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x04, 0x70, 0x6c, 0x61, 0x6e, 0x12, 0x30, 0x0a,
	0x05, 0x66, 0x65, 0x74, 0x63, 0x68, 0x18, 0x17, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73,
	0x6f, 0x75, 0x73, 0x6c, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x05, 0x66, 0x65, 0x74, 0x63, 0x68, 0x12,
	0x49, 0x0a, 0x0e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x73, 0x18, 0x18, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x6f, 0x75, 0x73, 0x6c, 0x65,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x0d, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x41, 0x0a, 0x0d, 0x68, 0x74,
	0x74, 0x70, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x18, 0x19, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x6f, 0x75, 0x73, 0x6c, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x48,
	0x54, 0x54, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x48, 0x00,
	0x52, 0x0b, 0x68, 0x74, 0x74, 0x70, 0x52, 0x65, 0x71, 0x48, 0x65, 0x61, 0x64, 0x12, 0x44, 0x0a,
	0x0e, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18,
	0x1a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x6f, 0x75, 0x73, 0x6c, 0x65, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x48, 0x54, 0x54, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x48, 0x00, 0x52, 0x0c, 0x68, 0x74, 0x74, 0x70, 0x52, 0x65, 0x71, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x12, 0x3f, 0x0a, 0x0d, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x5f, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x6f, 0x75,
	0x73, 0x6c, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x45, 0x0a, 0x0f, 0x75, 0x6e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x73, 0x6f, 0x75, 0x73, 0x6c, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x64, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x0e, 0x75, 0x6e, 0x64,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x39, 0x0a, 0x0b, 0x70,
	0x6c, 0x61, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x20, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x73, 0x6f, 0x75, 0x73, 0x6c, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c,
	0x61, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x6e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x42, 0x0a, 0x0e, 0x66, 0x65, 0x74, 0x63, 0x68, 0x5f,
	0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x21, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x73, 0x6f, 0x75, 0x73, 0x6c, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x0d, 0x66, 0x65, 0x74,
	0x63, 0x68, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x55, 0x0a, 0x15, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x5f, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x22, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x6f, 0x75, 0x73,
	0x6c, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x13, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x44, 0x0a, 0x0e, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x68,
	0x65, 0x61, 0x64, 0x18, 0x23, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x6f, 0x75, 0x73,
	0x6c, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x54, 0x54, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x48, 0x00, 0x52, 0x0c, 0x68, 0x74, 0x74, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x12, 0x47, 0x0a, 0x0f, 0x68, 0x74, 0x74, 0x70, 0x5f,
	0x72, 0x65, 0x73, 0x70, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x24, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x73, 0x6f, 0x75, 0x73, 0x6c, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x54,
	0x54, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x48,
	0x00, 0x52, 0x0d, 0x68, 0x74, 0x74, 0x70, 0x52, 0x65, 0x73, 0x70, 0x43, 0x68, 0x75, 0x6e, 0x6b,
	0x12, 0x35, 0x0a, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x28, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x6f, 0x75, 0x73, 0x6c, 0x65, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x48, 0x00, 0x52, 0x09, 0x68, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x29, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x29, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x6f, 0x75, 0x73, 0x6c, 0x65, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xd2, 0x01,
	0x0a, 0x0c, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6f, 0x6f, 0x6c, 0x5f,
	0x67, 0x69, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x70, 0x6f, 0x6f, 0x6c, 0x47,
	0x69, 0x62, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x5f, 0x67, 0x69,
	0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x47, 0x69, 0x62, 0x12, 0x3d, 0x0a, 0x0b, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x6f, 0x75, 0x73, 0x6c,
	0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0b, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x2e, 0x0a, 0x13, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x5f, 0x77, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x11, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x70,
	0x6f, 0x73, 0x22, 0x99, 0x01, 0x0a, 0x0f, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x69, 0x70,
	0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x50, 0x6f, 0x72, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x73, 0x5f, 0x67, 0x69, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x77, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x47, 0x69, 0x62, 0x12, 0x15, 0x0a, 0x06, 0x6b, 0x76, 0x5f, 0x67, 0x69,
	0x62, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x6b, 0x76, 0x47, 0x69, 0x62, 0x22, 0x80,
	0x01, 0x0a, 0x0d, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x5f, 0x79, 0x61, 0x6d, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x59, 0x61, 0x6d, 0x6c, 0x12, 0x1b,
	0x0a, 0x09, 0x77, 0x61, 0x6e, 0x74, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x77, 0x61, 0x6e, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x66,
	0x6f, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x72, 0x63,
	0x65, 0x22, 0x81, 0x01, 0x0a, 0x0c, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2e, 0x0a, 0x0f, 0x55, 0x6e, 0x64, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69,
	0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63,
	0x69, 0x70, 0x65, 0x49, 0x64, 0x22, 0x43, 0x0a, 0x0e, 0x55, 0x6e, 0x64, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x69,
	0x70, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4d, 0x0a, 0x0b, 0x50, 0x6c,
	0x61, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x63,
	0x69, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x63, 0x69, 0x70, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x69,
	0x6e, 0x67, 0x5f, 0x67, 0x69, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x69, 0x6e,
	0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x47, 0x69, 0x62, 0x22, 0x81, 0x01, 0x0a, 0x0a, 0x50, 0x6c,
	0x61, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x66, 0x69, 0x74, 0x73, 0x12, 0x23, 0x0a, 0x0d,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x5f, 0x67, 0x69, 0x62, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x47, 0x69,
	0x62, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x5f, 0x67, 0x69, 0x62, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x47, 0x69, 0x62,
	0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x75, 0x73, 0x74, 0x5f, 0x66, 0x72, 0x65, 0x65, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x75, 0x73, 0x74, 0x46, 0x72, 0x65, 0x65, 0x22, 0x22, 0x0a,
	0x0c, 0x46, 0x65, 0x74, 0x63, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x70,
	0x6f, 0x22, 0x65, 0x0a, 0x0d, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x62, 0x79, 0x74,
	0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x40, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x72, 0x65, 0x70, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x22, 0x60, 0x0a, 0x13, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x72, 0x65, 0x70, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x66,
	0x72, 0x65, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x46, 0x72, 0x65, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xbd, 0x01, 0x0a,
	0x0f, 0x48, 0x54, 0x54, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x42, 0x0a, 0x07,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e,
	0x73, 0x6f, 0x75, 0x73, 0x6c, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x54, 0x54, 0x50, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x1a, 0x3a, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x38, 0x0a, 0x10,
	0x48, 0x54, 0x54, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x68, 0x75, 0x6e, 0x6b,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6f, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x03, 0x65, 0x6f, 0x66, 0x22, 0xab, 0x01, 0x0a, 0x10, 0x48, 0x54, 0x54, 0x50, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x43, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x73, 0x6f, 0x75, 0x73, 0x6c, 0x65, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x48, 0x54, 0x54, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65,
	0x61, 0x64, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x39, 0x0a, 0x11, 0x48, 0x54, 0x54, 0x50, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a,
	0x03, 0x65, 0x6f, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x65, 0x6f, 0x66, 0x22,
	0x2e, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x21, 0x0a, 0x0c,
	0x75, 0x6e, 0x69, 0x78, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x75, 0x6e, 0x69, 0x78, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22,
	0x21, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0x44, 0x0a, 0x07, 0x53, 0x6f, 0x75, 0x73, 0x6c, 0x65, 0x74, 0x12, 0x39, 0x0a,
	0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x14, 0x2e, 0x73, 0x6f, 0x75, 0x73, 0x6c,
	0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x1a, 0x14,
	0x2e, 0x73, 0x6f, 0x75, 0x73, 0x6c, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x76, 0x65,
	0x6c, 0x6f, 0x70, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x6d, 0x75, 0x67, 0x2f, 0x73,
	0x6f, 0x75, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f,
	0x73, 0x6f, 0x75, 0x73, 0x6c, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_souslet_v1_souslet_proto_rawDescOnce sync.Once
	file_proto_souslet_v1_souslet_proto_rawDescData = file_proto_souslet_v1_souslet_proto_rawDesc
)

func file_proto_souslet_v1_souslet_proto_rawDescGZIP() []byte {
	file_proto_souslet_v1_souslet_proto_rawDescOnce.Do(func() {
		file_proto_souslet_v1_souslet_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_souslet_v1_souslet_proto_rawDescData)
	})
	return file_proto_souslet_v1_souslet_proto_rawDescData
}

var file_proto_souslet_v1_souslet_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_souslet_v1_souslet_proto_goTypes = []any{
	(*Envelope)(nil),             // 0: souslet.v1.Envelope
	(*NodeSnapshot)(nil),         // 1: souslet.v1.NodeSnapshot
	(*DeploymentState)(nil),      // 2: souslet.v1.DeploymentState
	(*DeployCommand)(nil),        // 3: souslet.v1.DeployCommand
	(*DeployResult)(nil),         // 4: souslet.v1.DeployResult
	(*UndeployCommand)(nil),      // 5: souslet.v1.UndeployCommand
	(*UndeployResult)(nil),       // 6: souslet.v1.UndeployResult
	(*PlanCommand)(nil),          // 7: souslet.v1.PlanCommand
	(*PlanResult)(nil),           // 8: souslet.v1.PlanResult
	(*FetchCommand)(nil),         // 9: souslet.v1.FetchCommand
	(*FetchProgress)(nil),        // 10: souslet.v1.FetchProgress
	(*DeleteWeightsCommand)(nil), // 11: souslet.v1.DeleteWeightsCommand
	(*DeleteWeightsResult)(nil),  // 12: souslet.v1.DeleteWeightsResult
	(*HTTPRequestHead)(nil),      // 13: souslet.v1.HTTPRequestHead
	(*HTTPRequestChunk)(nil),     // 14: souslet.v1.HTTPRequestChunk
	(*HTTPResponseHead)(nil),     // 15: souslet.v1.HTTPResponseHead
	(*HTTPResponseChunk)(nil),    // 16: souslet.v1.HTTPResponseChunk
	(*Heartbeat)(nil),            // 17: souslet.v1.Heartbeat
	(*Error)(nil),                // 18: souslet.v1.Error
	nil,                          // 19: souslet.v1.HTTPRequestHead.HeadersEntry
	nil,                          // 20: souslet.v1.HTTPResponseHead.HeadersEntry
}
var file_proto_souslet_v1_souslet_proto_depIdxs = []int32{
	1,  // 0: souslet.v1.Envelope.snapshot:type_name -> souslet.v1.NodeSnapshot
	3,  // 1: souslet.v1.Envelope.deploy:type_name -> souslet.v1.DeployCommand
	5,  // 2: souslet.v1.Envelope.undeploy:type_name -> souslet.v1.UndeployCommand
	7,  // 3: souslet.v1.Envelope.plan:type_name -> souslet.v1.PlanCommand
	9,  // 4: souslet.v1.Envelope.fetch:type_name -> souslet.v1.FetchCommand
	11, // 5: souslet.v1.Envelope.delete_weights:type_name -> souslet.v1.DeleteWeightsCommand
	13, // 6: souslet.v1.Envelope.http_req_head:type_name -> souslet.v1.HTTPRequestHead
	14, // 7: souslet.v1.Envelope.http_req_chunk:type_name -> souslet.v1.HTTPRequestChunk
	4,  // 8: souslet.v1.Envelope.deploy_result:type_name -> souslet.v1.DeployResult
	6,  // 9: souslet.v1.Envelope.undeploy_result:type_name -> souslet.v1.UndeployResult
	8,  // 10: souslet.v1.Envelope.plan_result:type_name -> souslet.v1.PlanResult
	10, // 11: souslet.v1.Envelope.fetch_progress:type_name -> souslet.v1.FetchProgress
	12, // 12: souslet.v1.Envelope.delete_weights_result:type_name -> souslet.v1.DeleteWeightsResult
	15, // 13: souslet.v1.Envelope.http_resp_head:type_name -> souslet.v1.HTTPResponseHead
	16, // 14: souslet.v1.Envelope.http_resp_chunk:type_name -> souslet.v1.HTTPResponseChunk
	17, // 15: souslet.v1.Envelope.heartbeat:type_name -> souslet.v1.Heartbeat
	18, // 16: souslet.v1.Envelope.error:type_name -> souslet.v1.Error
	2,  // 17: souslet.v1.NodeSnapshot.deployments:type_name -> souslet.v1.DeploymentState
	19, // 18: souslet.v1.HTTPRequestHead.headers:type_name -> souslet.v1.HTTPRequestHead.HeadersEntry
	20, // 19: souslet.v1.HTTPResponseHead.headers:type_name -> souslet.v1.HTTPResponseHead.HeadersEntry
	0,  // 20: souslet.v1.Souslet.Connect:input_type -> souslet.v1.Envelope
	0,  // 21: souslet.v1.Souslet.Connect:output_type -> souslet.v1.Envelope
	21, // [21:22] is the sub-list for method output_type
	20, // [20:21] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_souslet_v1_souslet_proto_init() }
func file_proto_souslet_v1_souslet_proto_init() {
	if File_proto_souslet_v1_souslet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_souslet_v1_souslet_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Envelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_souslet_v1_souslet_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*NodeSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_souslet_v1_souslet_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*DeploymentState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_souslet_v1_souslet_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DeployCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_souslet_v1_souslet_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DeployResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_souslet_v1_souslet_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UndeployCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_souslet_v1_souslet_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UndeployResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_souslet_v1_souslet_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*PlanCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_souslet_v1_souslet_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*PlanResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_souslet_v1_souslet_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*FetchCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_souslet_v1_souslet_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*FetchProgress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_souslet_v1_souslet_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteWeightsCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_souslet_v1_souslet_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteWeightsResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_souslet_v1_souslet_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*HTTPRequestHead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_souslet_v1_souslet_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*HTTPRequestChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_souslet_v1_souslet_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*HTTPResponseHead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_souslet_v1_souslet_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*HTTPResponseChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_souslet_v1_souslet_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*Heartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_souslet_v1_souslet_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_souslet_v1_souslet_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Snapshot)(nil),
		(*Envelope_Deploy)(nil),
		(*Envelope_Undeploy)(nil),
		(*Envelope_Plan)(nil),
		(*Envelope_Fetch)(nil),
		(*Envelope_DeleteWeights)(nil),
		(*Envelope_HttpReqHead)(nil),
		(*Envelope_HttpReqChunk)(nil),
		(*Envelope_DeployResult)(nil),
		(*Envelope_UndeployResult)(nil),
		(*Envelope_PlanResult)(nil),
		(*Envelope_FetchProgress)(nil),
		(*Envelope_DeleteWeightsResult)(nil),
		(*Envelope_HttpRespHead)(nil),
		(*Envelope_HttpRespChunk)(nil),
		(*Envelope_Heartbeat)(nil),
		(*Envelope_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_souslet_v1_souslet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_souslet_v1_souslet_proto_goTypes,
		DependencyIndexes: file_proto_souslet_v1_souslet_proto_depIdxs,
		MessageInfos:      file_proto_souslet_v1_souslet_proto_msgTypes,
	}.Build()
	File_proto_souslet_v1_souslet_proto = out.File
	file_proto_souslet_v1_souslet_proto_rawDesc = nil
	file_proto_souslet_v1_souslet_proto_goTypes = nil
	file_proto_souslet_v1_souslet_proto_depIdxs = nil
}
