// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.13.0
// source: proto/souslet/v1/souslet.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Souslet_Connect_FullMethodName = "/souslet.v1.Souslet/Connect"
)

// SousletClient is the client API for Souslet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SousletClient interface {
	// souslet dials this once and keeps it open for the process lifetime.
	// Every deploy/fetch/proxy operation sous-api needs this node to do is
	// an Envelope on this stream; souslet executes it locally and streams
	// results back on the same stream, correlated by stream_id.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Envelope, Envelope], error)
}

type sousletClient struct {
	cc grpc.ClientConnInterface
}

func NewSousletClient(cc grpc.ClientConnInterface) SousletClient {
	return &sousletClient{cc}
}

func (c *sousletClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Envelope, Envelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Souslet_ServiceDesc.Streams[0], Souslet_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Envelope, Envelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Souslet_ConnectClient = grpc.BidiStreamingClient[Envelope, Envelope]

// SousletServer is the server API for Souslet service.
// All implementations must embed UnimplementedSousletServer
// for forward compatibility.
type SousletServer interface {
	// souslet dials this once and keeps it open for the process lifetime.
	// Every deploy/fetch/proxy operation sous-api needs this node to do is
	// an Envelope on this stream; souslet executes it locally and streams
	// results back on the same stream, correlated by stream_id.
	Connect(grpc.BidiStreamingServer[Envelope, Envelope]) error
	mustEmbedUnimplementedSousletServer()
}

// UnimplementedSousletServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSousletServer struct{}

func (UnimplementedSousletServer) Connect(grpc.BidiStreamingServer[Envelope, Envelope]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedSousletServer) mustEmbedUnimplementedSousletServer() {}
func (UnimplementedSousletServer) testEmbeddedByValue()                 {}

// UnsafeSousletServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SousletServer will
// result in compilation errors.
type UnsafeSousletServer interface {
	mustEmbedUnimplementedSousletServer()
}

func RegisterSousletServer(s grpc.ServiceRegistrar, srv SousletServer) {
	// If the following call pancis, it indicates UnimplementedSousletServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Souslet_ServiceDesc, srv)
}

func _Souslet_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SousletServer).Connect(&grpc.GenericServerStream[Envelope, Envelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Souslet_ConnectServer = grpc.BidiStreamingServer[Envelope, Envelope]

// Souslet_ServiceDesc is the grpc.ServiceDesc for Souslet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Souslet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "souslet.v1.Souslet",
	HandlerType: (*SousletServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Souslet_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/souslet/v1/souslet.proto",
}
